server:
  port: 8083
spring:
  application:
    name: gateway-library
  cloud:
    gateway:
      routes:
        - id: book-microservice
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/book/**
        - id: loan-microservice
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/loan/**
  datasource:
    url: ${USER_DB}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
secret:
  key: ${SECRET_KEY}
init:
  names: ${INIT_NAMES}
  username: ${INIT_USERNAME}
  password: ${INIT_PASSWORD}
  role: ${INIT_ROLE}